name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: sh gradlew cleanTest test --tests tests.allure.GitHubIssueTests -Dselenide.headless=true

      - name: Generate Allure report
        if: always()
        run: sh gradlew allureReport --clean

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test
          if-no-files-found: ignore

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results
          if-no-files-found: ignore

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report/allureReport
          if-no-files-found: ignore
